name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
       # Filepath of the project to be packaged, relative to root of repository
       PROJECT_FILE_PATH: ./Raven.NET/Raven.NET.Core.csproj
       # NuGet package id, used for version detection & defaults to project name

       NUGET_KEY: # optional
