name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Build
      run: dotnet build --no-restore ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Build NuGet
      run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj --output ./Raven.NET.Core /p:Version=${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-alpha
      
    - name: Set Api Key
      run: nuget setapikey ${{ secrets.NUGET_SECRET }}
    
    - name: Publish NuGet
      run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-alpha.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_SECRET }}

  publishAlpha:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build NuGet
      run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj --output ./Raven.NET.Core /p:Version=${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-rc

    - name: Set Api Key
      run: nuget setapikey ${{ secrets.NUGET_SECRET }}

    - name: Publish NuGet
      run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-rc.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_SECRET }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build NuGet
        run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj --output ./Raven.NET.Core /p:Version=${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}

      - name: Set Api Key
        run: nuget setapikey ${{ secrets.NUGET_SECRET }}

      - name: Publish NuGet
        run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_SECRET }}
