name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Build
      run: dotnet build --no-restore ./Raven.NET.Core/Raven.NET.Core.csproj

    - name: echo
      run: echo ${{ github.ref }} ${{ github.event_name }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ./Raven.NET.Core.Tests/Raven.NET.Core.Tests.csproj
    - name: echo
      run: echo ${{ github.ref }} ${{ github.event_name }}


  publishRC:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.base.ref == 'main'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build NuGet
      run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj --output ./Raven.NET.Core /p:Version=${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-rc

    - name: Set Api Key
      run: nuget setapikey ${{ secrets.NUGET_SECRET }}

    - name: Publish NuGet
      run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.${{ github.run_number }}-rc.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_SECRET }}

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{  github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build NuGet
        run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj --output ./Raven.NET.Core /p:Version=${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.0

      - name: Set Api Key
        run: nuget setapikey ${{ secrets.NUGET_SECRET }}

      - name: Publish NuGet
        run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.${{ secrets.NUGET_MAJOR_VERSION }}.${{ secrets.NUGET_MINOR_VERSION }}.0.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_SECRET }}
