name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Build
      run: dotnet build --no-restore ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Raven.NET.Core/Raven.NET.Core.csproj
    - name: Build NuGet
      run: dotnet pack ./Raven.NET.Core/Raven.NET.Core.csproj /p:Version=$(Build.BuildNumber)
      
    - name: Publish NuGet
      run: dotnet nuget push ./Raven.NET.Core/Raven.NET.Core.$(Build.BuildNumber).nupkg --source https://api.nuget.org/v3/index.json
